language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install -g npm-run-all start-server-and-test
script:
  - npm install
  - npm run test-headless
  - ng build --prod
  - npm run e2e
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "Xz2pQn38mZJjPTFxCeTXCUsmGrbGy/XsBteW419PGBQzdkbUPI1H6De0I/s1QQmUw32z9Sv/jIa0WEA/bXQGJh2KX/ywOnxP6fuME82y4vSS8pXiUhyksOiZRDSMHP3/uP+ZYqNU5ai1maxP2gR+Kn7yjP3FxcZ10TM6rrs2+gXvYs/eHV8+sM7Bwzix1a434QRO504HJc6DEp9b7aGcrPBvEoJ4O+VfAP1Dwpvoqb4UyDXimuyAtQ7GA0Q4b2cbAREDB/gnk0IJubGC+pyaZ+HAGR1/GwXnCt+tHncSZSszk06gQpVZhgiNwnsnRdQyW7o9WKCfy50avFLgcG0BSFAUBMO/3dxLzob/3yvLEViwfoMKByO76GX5xhuDI7Ttagv90N3pDgP7DyM3waPd5yOWRJb8sa/kM9Y3jzKk7+JZj4OQqEG0MK9BxTIb8zG7ShJ/zoMd7mMyVWE4SNa9d4r/P7S9dFOG/6vBE/0dsaTXM1MziVFJOdplF3nxNdLax7vK2T1IvTVGL1+QTIhC1/yT35dtF9wjE/56243kc338FV9jZodNVaF7yQMT8H/UJ2cn8gOKPKUlpnlpudYYrAWB27AcbmXXD9OH5zG+gy8k33jHCC8srBzPKDvErig6L/8NOoHKGF1yLUWl/GCjTJLERwtWYixui+flAKL71Q4="
