language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1//039eh95nxRCkoCgYIARAAGAMSNwF-L9Iri2ei2IRCAyPHWTLmI348ttuNLGAh3GurfyBm3tyTcqUessf2OWSNACp9TgpYDOQDINY"
